name: .NET Core Testing Workflows

on:
  push:
    branches: [ 'main', 'dev', 'feature/*', 'hotfix/*', 'bugfix/*' ]
  pull_request:
    branches: [ 'main', 'dev', 'feature/*', 'hotfix/*', 'bugfix/*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.400'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      working-directory: GitHubService/GitHubService
      run: dotnet build "GitHubService" --no-restore
  domain-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing API
      working-directory: GitHubService/GitHubService
      run: dotnet test "GitHubService.Domain" --no-build --verbosity normal
  api-test:
    needs: domain-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing API
      working-directory: GitHubService/GitHubService
      run: dotnet test "GitHubService.API" --no-build --verbosity normal
